### ISSUE TITLE
L'évaluation forfaitaire des charges locatives semble être un doublon de celle de la CAF

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/openfisca-paris#3]
`paris_charges_forfaitaire_logement` et `aide_logement_charges` semblent calculer la même chose.

@kinta95, peux tu me confirmer que la variable [paris_charges_forfaitaire_logement](https://github.com/sgmap/openfisca-paris/blob/paris/paris.py#L245) sert juste à calculer le montant des charges locatives tel qu'évalué de manière forfaitaire par la CAF ?

Si oui pas besoin de le recalculer, c'est déjà fait dans openfisca :)

**Comment by guillett** [comment]
La version implémentée dans ce dépôt a déjà été supprimée et remplacée par [`aide_logement_charges`](https://legislation.openfisca.fr/aide_logement_charges) dans le commit 225ebcb9e61ef10d1cbf1083aa714dff5a148f5a.

@kinta95 pourrais-tu confirmer/infirmer que la variable `paris_charges_forfaitaire_logement` servait à calculer le montant des charges locatives tel qu'évalué de manière forfaitaire par la CAF ?

Merci.

**Comment by kinta95** [comment]
Je vous confirme que la variable paris_charges_forfaitaire_logement servait à calculer les charges forfaitaires de la CAF.

Kinta

De : Thomas Guillet [mailto:notifications@github.com]
Envoyé : vendredi 28 juillet 2017 08:25
À : sgmap/openfisca-paris <openfisca-paris@noreply.github.com>
Cc : Kinta MENDY <kinta.mendy@implicit.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sgmap/openfisca-paris] L'évaluation forfaitaire des charges locatives semble être un doublon de celle de la CAF (#3)


La version implémentée dans ce dépôt a déjà été supprimée et remplacée par aide_logement_charges<https://legislation.openfisca.fr/aide_logement_charges> dans le commit 225ebcb<https://github.com/sgmap/openfisca-paris/commit/225ebcb9e61ef10d1cbf1083aa714dff5a148f5a>.

@kinta95<https://github.com/kinta95> pourrais-tu confirmer/infirmer que la variable paris_charges_forfaitaire_logement servait à calculer le montant des charges locatives tel qu'évalué de manière forfaitaire par la CAF ?

Merci.

**Comment by guillett** [comment]
Super @kinta95 merci beaucoup.
Je ferme cet issue.
